# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: rust:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
# cache:
  # paths:
    # - node_modules/

pages:
  script:
    - cargo install wasm-pack
    - wasm-pack build --target web
    - mv pkg/jsondiff.js public
    - mkdir public
    - cp -r web public
  artifacts:
    paths:
      - public
  only:
    - master

cache:
  paths:
    - cargo/
